### ISSUE TITLE
Function and variable signatures look too "compressed"

### ISSUE THREAD

**Issue by parkerhoyes** [snide/sphinx_rtd_theme#322]
I don't know if this is just me being nitpicky, but the spacing between words in function and variable signatures seems to be too close together. Here's a picture:

![before](https://cloud.githubusercontent.com/assets/6626143/18213957/aaa6a4c0-7118-11e6-8192-c4d989d3d67e.png)

With a little bit of CSS tweaking in the browser I was able to achieve this effect:

![after](https://cloud.githubusercontent.com/assets/6626143/18213980/c6c442e8-7118-11e6-92d0-0df89b015737.png)

All I did was add the following CSS:
```css
.rst-content dl:not(.docutils) dt {
    word-spacing: 4px;
}
```
I was also able to add spacing only before the function / variable name like so:

![code-only](https://cloud.githubusercontent.com/assets/6626143/18214151/73251800-7119-11e6-9038-b64dea7d9aef.png)

This effect was achieving by adding the following CSS:
```css
.rst-content dl:not(.docutils).function code.descname, .rst-content dl:not(.docutils).member code.descname, .rst-content dl:not(.docutils).var code.descname {
    padding-left: 4px;
}
```
Let me know what you guys think. If this is a change you'd like to make, I can modify the SASS code and submit a PR if you'd like.
